import Foundation

/// Emergency and road hotlines bundled offline (StarterData/hotlines.json, generated by
/// scripts/build_hotlines.py from official pages, each with its source and retrieval date).
/// Lookup is deterministic: no model ever produces a phone number.
public struct Hotline: Codable, Hashable, Sendable, Identifiable {
    public enum Group: String, Codable, Sendable { case national, expressway, lgu }
    public var id: String
    public var group: Group
    public var name: String
    public var numbers: [String]
    /// Words that pick this entry ("nlex", "makati", "red cross", "bumbero").
    public var aliases: [String]
    public var sourceName: String
    public var sourceURL: String
    public var retrieved: String
    /// "official" (government or operator page) or "secondary" (news or directory).
    public var confidence: String

    /// Digits only, for tel: links ("(02) 8870-1000" -> "0288701000"; "911" stays "911").
    public static func dialable(_ number: String) -> String { number.filter(\.isNumber) }
}

public struct HotlineDirectory: Sendable {
    public let entries: [Hotline]
    /// Region pack id -> LGU entry id for "your city" numbers.
    public let regionLGU: [String: String]

    private struct Raw: Codable { var hotlines: [Hotline]; var regionLGU: [String: String] }

    public init(entries: [Hotline], regionLGU: [String: String] = [:]) { self.entries = entries; self.regionLGU = regionLGU }

    public static func decode(_ data: Data) throws -> HotlineDirectory {
        let raw = try JSONDecoder().decode(Raw.self, from: data)
        return HotlineDirectory(entries: raw.hotlines, regionLGU: raw.regionLGU)
    }

    static let askWords: [[String]] = [["number"], ["numero"], ["hotline"], ["hotlines"], ["contact"], ["telepono"],
                                       ["phone"], ["tawagan"], ["tatawagan"], ["matawagan"], ["tumawag", "sa"],
                                       ["call", "who"], ["sino", "tatawagan"], ["emergency", "number"]]

    /// "Ano ang number ng highway patrol?", "hotline ng NLEX", "sino tatawagan sa Makati".
    public func isAsking(_ text: String) -> Bool {
        let words = SafetyLexicon.normalize(text)
        return Self.askWords.contains { SafetyLexicon.matches($0, in: words) }
    }

    /// Entries named in the text (by alias), in file order.
    public func named(in text: String) -> [Hotline] {
        let words = SafetyLexicon.normalize(text)
        return entries.filter { entry in entry.aliases.contains { SafetyLexicon.matches(SafetyLexicon.normalize($0), in: words) } }
    }

    public func entry(_ id: String) -> Hotline? { entries.first { $0.id == id } }

    /// The LGU entry for a region pack (nil for the main-roads pack or an unknown region).
    public func local(regionID: String?) -> Hotline? { regionID.flatMap { regionLGU[$0] }.flatMap(entry) }

    /// Answer for a hotline question: what was named, else 911 + your city + the other national lines.
    public func answer(for text: String, regionID: String?) -> [Hotline] {
        let named = named(in: text)
        if !named.isEmpty { return named }
        var out = entries.filter { $0.group == .national }
        if let local = local(regionID: regionID) { out.insert(local, at: min(1, out.count)) }
        return out
    }

    /// Shown under an emergency answer, after the 911 button: your city's rescue line and the
    /// national ones that send help (ambulance, fire), at most three.
    public func forEmergency(regionID: String?) -> [Hotline] {
        var out: [Hotline] = []
        if let local = local(regionID: regionID) { out.append(local) }
        out += entries.filter { $0.group == .national && $0.id != "911" }.prefix(3 - out.count)
        return out
    }
}
