#!/usr/bin/env python3
"""Writes LifeOffDesk/Resources/StarterData/safety-guide.json: help cards paraphrased from the linked public sources (see docs/SAFETY-GUIDE.md). Edit cards here, then run it."""
import json
APP = ("Life Off Desk app guidance (not medical)", "https://github.com/lewisjohnvillamor/Lifeoffdesk/blob/main/docs/SAFETY-GUIDE.md")
cards = [
 ("bleeding","Cuts and bleeding",[
  "Wash and dry your hands; wear disposable gloves if you have them.",
  "Press on the wound with a bandage or clean folded cloth.",
  "If something is stuck in it, leave it in and press firmly on either side.",
  "Raise an injured arm above head level; for a leg, lie down and raise it above the heart.",
  "If blood soaks through, add another pad on top and keep pressing.",
  "Every 10 minutes check the bandage isn't too tight."],
  ["The bleeding won't stop","Bright red blood spurts out","Numbness near the wound or trouble moving it","A very large or deep wound, or one on the face or palm","An object like glass is stuck in it"],
  "Cuts and grazes - NHS","https://www.nhs.uk/conditions/cuts-and-grazes/"),
 ("burn","Burns and scalds",[
  "Cool the burn under cool running water for 20 minutes.",
  "No tap? Use cool bottled water or a wet towel.",
  "Remove clothing or jewellery near the burn, but not anything stuck to it.",
  "Once cooled, lay cling film loosely over it; don't wrap it around.",
  "Don't use creams, oil, butter, plasters or sticky dressings; don't burst blisters."],
  ["The burn is very large or deep","It is on the face, genitals or bottom","It was caused by acid, chemicals or electricity"],
  "Burns and scalds - NHS","https://www.nhs.uk/conditions/burns-and-scalds/"),
 ("sprain","Sprains, twisted ankles and possible broken bones",[
  "Protect: support the injury, for example with supportive shoes.",
  "Rest: stop and avoid putting weight on it.",
  "Ice: a wrapped ice pack for up to 20 minutes, every 2–3 hours.",
  "Compression: wrap a bandage around it for support during the day.",
  "Elevate: keep it raised on a pillow as much as possible.",
  "For the first couple of days avoid heat, alcohol and massage."],
  ["You heard a crack when it happened","The limb looks misshapen or at an odd angle","It is numb or tingling","The skin is blue, grey or cold"],
  "Sprains and strains - NHS","https://www.nhs.uk/conditions/sprains-and-strains/"),
 ("heat","Heat exhaustion and heatstroke",[
  "Move the person somewhere cool.",
  "Remove unnecessary clothing like jackets or socks.",
  "Give plenty of water; a sports drink or oral rehydration solution also helps.",
  "Spray or sponge with cool water and fan them; put wrapped cold packs on armpits or neck.",
  "Stay with them; they should feel better within 30 minutes.",
  "If unconscious, use the recovery position; give CPR if there are no signs of life."],
  ["Still unwell after 30 minutes of cooling and fluids","Hot skin that isn't sweating","Fast heartbeat or fast breathing","Confusion or poor coordination","A seizure or loss of consciousness"],
  "Heat exhaustion and heatstroke - NHS","https://www.nhs.uk/conditions/heat-exhaustion-heatstroke/"),
 ("fainting","Fainting and feeling faint",[
  "Feeling faint? Lie down with legs raised, or sit with your head between your knees.",
  "Drink some water; cross your legs, rock on your toes or clench your fists.",
  "If someone faints, gently shake their shoulders and ask loudly if they're OK.",
  "No response: shout for help, tilt the head back and lift the chin.",
  "Check breathing for 10 seconds; if normal, lay them on their back with legs raised.",
  "Most people wake within 30 seconds."],
  ["They are not breathing","They can't be woken within 1 minute","Trouble speaking or moving, chest pain or palpitations","A seizure, a serious injury, or fainting while exercising or lying down"],
  "Fainting - NHS","https://www.nhs.uk/symptoms/fainting/"),
 ("choking","Choking (adult)",[
  "Ask \"are you choking?\" If they can breathe, speak or cough, let them cough.",
  "Remove any obvious blockage from the mouth.",
  "If coughing fails, lean them forward and give five sharp back blows between the shoulder blades.",
  "Check the mouth after each back blow.",
  "Still blocked: stand behind, fist between belly button and chest, pull sharply in and up, up to five times.",
  "Keep repeating five back blows and five thrusts until help arrives."],
  ["The blockage hasn't cleared after back blows and thrusts","They become unresponsive (start CPR)"],
  "Choking | St John Ambulance","https://www.sja.org.uk/first-aid-advice/choking/"),
 ("cpr","CPR (adult, not breathing)",[
  "Make sure it's safe; shake their shoulders and ask loudly \"are you OK?\"",
  "No response: shout for help, tilt the head back, check normal breathing for up to 10 seconds.",
  "Not breathing normally: have someone call 911 on speaker and find a defibrillator.",
  "Heel of your hand mid-chest, other hand on top, arms straight, press down 5–6 cm.",
  "Push 100–120 times a minute. Not trained? Keep giving continuous chest compressions.",
  "Continue until help takes over, they breathe normally, or you are exhausted."],
  ["An adult is unresponsive and not breathing normally (occasional gasps are not normal breathing)"],
  "How to do CPR | St John Ambulance","https://www.sja.org.uk/get-advice/first-aid-advice/unresponsive-casualty/how-to-do-cpr-on-an-adult/"),
 ("allergy","Severe allergic reaction (anaphylaxis)",[
  "Use an adrenaline auto-injector (e.g. EpiPen) if there is one; instructions are on the side.",
  "Call 911 and say you think it's anaphylaxis.",
  "Lie down with legs raised; if breathing is hard, sit up slowly.",
  "If stung, remove the sting if it's still in the skin.",
  "No improvement after 5 minutes: use a second auto-injector.",
  "Never stand or walk, even if feeling better."],
  ["Lips, mouth, throat or tongue suddenly swell","Breathing is fast or a struggle, or the throat feels tight","Skin, tongue or lips turn blue, grey or pale","Sudden confusion, drowsiness, or fainting"],
  "Anaphylaxis - NHS","https://www.nhs.uk/conditions/anaphylaxis/"),
 ("animalBite","Dog or cat bite or scratch (rabies risk)",[
  "Wash the wound right away with soap or detergent.",
  "Flush it with plenty of water for about 15 minutes.",
  "Then apply an iodine-containing or antiviral antiseptic if you have one.",
  "Don't put chili, plant juices, acids or alkalis on it.",
  "Go to a health facility for assessment and rabies treatment; don't wait.",
  "If it's safe, keep the animal confined and watch it for 10 days."],
  ["Any bite or scratch from an animal that could have rabies: get medical care today","A large or deep wound, or bleeding that won't stop"],
  "Rabies - World Health Organization","https://www.who.int/health-topics/rabies"),
 ("dehydration","Dehydration",[
  "Drink fluids if you are thirsty, dizzy, tired, or your pee is dark.",
  "If you feel sick, start with small sips and slowly drink more.",
  "Avoid caffeine and alcohol.",
  "With vomiting or diarrhoea, use oral rehydration solution.",
  "Drink more in hot weather or when exercising; aim for pale pee."],
  ["Blue, grey, pale or blotchy skin, lips or tongue, or cold skin","Difficulty breathing or rapid breaths","Confusion, or being unusually sleepy or hard to wake"],
  "Dehydration - NHS","https://www.nhs.uk/conditions/dehydration/"),
 ("sting","Insect and bee stings",[
  "Scrape the stinger out sideways with a fingernail or card edge.",
  "Don't use tweezers; squeezing can push in more venom.",
  "Wash the area with soap and water.",
  "Hold a wrapped ice pack or cold wet cloth on it for at least 20 minutes; raise it.",
  "Don't scratch."],
  ["Stung in the mouth, throat or near the eyes","Stung many times, or a serious reaction before","Any sign of anaphylaxis: swelling of lips or throat, trouble breathing"],
  "Insect bites and stings - NHS","https://www.nhs.uk/conditions/insect-bites-and-stings/"),
 ("snakeBite","Snake bite",[
  "Treat every snake bite as an emergency: call 911 or go to a hospital.",
  "Stay calm and keep the bitten part as still as possible.",
  "Remove jewellery and loosen clothing near the bite.",
  "Remember the snake's colour and pattern, or photograph it from a safe distance.",
  "Don't catch or kill the snake, suck or cut the bite, or tie anything tight around it."],
  ["Any snake bite"],
  "Snake bites - NHS (UK page; outside the UK use local emergency services)","https://www.nhs.uk/conditions/snake-bites/"),
 ("wildPlants","Wild plants, berries and mushrooms",[
  "This app cannot identify plants or mushrooms, and a description is not enough to know one is safe.",
  "Some plants and mushrooms are poisonous; if someone may have eaten one, call 911 or go to a hospital.",
  "Don't make them vomit, and don't give them anything to eat or drink.",
  "Keep a sample of what was eaten to show the doctors.",
  "If unconscious but breathing, use the recovery position; if not breathing, start CPR."],
  ["Something harmful may have been eaten (symptoms can take hours or days)","Unconscious, not breathing, or breathing is very difficult","A seizure"],
  "Poisoning - NHS","https://www.nhs.uk/conditions/poisoning/"),
 ("flood","Floods (baha)",[
  "Don't walk or drive through flooded areas or standing water.",
  "Hidden dangers include fallen power lines and chemicals; currents can sweep people away.",
  "Know your community's evacuation route and flood-prone areas.",
  "Wash hands with soap after touching floodwater; never use it for food, dishes or teeth.",
  "Throw away food that touched floodwater; boil or chlorinate drinking water."],
  ["Someone is trapped or swept away by water","Live wires are down in or near the water"],
  "Floods: How to protect your health - WHO","https://www.who.int/news-room/questions-and-answers/item/how-do-i-protect-my-health-in-a-flood"),
 ("lightning","Lightning and thunderstorms",[
  "When thunder roars, go indoors: hearing thunder means you're within striking distance.",
  "Only an enclosed building or a car is safe; tents and open shelters are not.",
  "Wait 30 minutes after the last thunder before going back outside.",
  "If stuck outside, avoid open fields, hilltops and tall isolated trees.",
  "Groups should spread out; stay away from water and metal fences or poles."],
  [],
  "Lightning Safety - US National Weather Service","https://www.weather.gov/safety/lightning-safety"),
 ("unsafe","Feeling unsafe, followed or threatened",[
  "If you are in danger now, call 911.",
  "Go towards people and lit, busy places such as a store, guard post or police station.",
  "In this Help screen, the nearest police stations have a Route button (offline).",
  "Copy or text your location from this screen to someone you trust (SMS works without data)."],
  ["You or someone else is in immediate danger"],
  *APP),
 ("lost","Lost or not sure where you are",[
  "Stay calm and stop walking for a moment.",
  "Tap Locate on the map; your position works offline while GPS has a fix.",
  "Copy or text your location from this Help screen to someone you trust.",
  "Pick a place on the map and follow the dashed suggested route along mapped streets."],
  ["You are hurt, in danger, or it is getting dark somewhere unsafe"],
  *APP),
 ("phoneBattery","Phone battery running low",[
  "Turn on Low Power Mode: Settings › Battery (or Control Center, battery icon).",
  "Low Power Mode dims the screen and pauses background tasks to save battery.",
  "With no signal, Airplane Mode stops the phone searching for a network, which drains battery.",
  "Before it runs out, text your location to someone you trust."],
  [],
  "Use Low Power Mode to save battery life on your iPhone - Apple Support","https://support.apple.com/en-us/101604"),
 ("noGPS","Location not updating",[
  "This app works without data; GPS itself needs no signal or internet.",
  "If the app says \"Finding your location…\", move to an open area away from tall buildings and wait a moment.",
  "Check Settings › Privacy & Security › Location Services is on for Life Off Desk.",
  "Your last saved adventure and the map still work while the location catches up."],
  [],
  *APP),
 ("breakdown","Vehicle breakdown: stay safe first",[
  "Get the vehicle off the road if you can, ideally a parking area or lay-by.",
  "Turn on hazard lights if the vehicle is blocking traffic.",
  "Wear light or reflective clothing; keep sidelights on if it's dark.",
  "Place a warning triangle at least 45 m behind the vehicle, on the same side.",
  "Passengers should keep well away from the vehicle and moving traffic.",
  "Never stand between your vehicle and oncoming traffic."],
  ["You can't get out safely: stay inside with seat belts and hazards on, and call 911","On a high-speed road: don't attempt repairs; get behind a barrier"],
  "The Highway Code: Breakdowns and incidents - GOV.UK","https://www.gov.uk/guidance/the-highway-code/breakdowns-and-incidents-274-to-287"),
 ("flatTire","Flat tire (gulong): changing to the spare",[
  "Park somewhere safe away from traffic: engine off, hazards on, handbrake on, in park or first gear.",
  "Loosen the wheel nuts slightly before jacking the car up.",
  "Jack at the marked jacking point (see the handbook) on level ground until the wheel is off the ground.",
  "Remove the nuts and wheel, fit the spare, hand-tighten the nuts in a diagonal pattern.",
  "Lower the car, tighten the nuts firmly, then check the tire pressure.",
  "Go to a vulcanizing or tire shop soon; space-saver spares are usually limited to about 80 km/h."],
  ["Never change a tire on an expressway shoulder or next to fast traffic","If the wheel won't come off easily, refit the nuts and call for help","If a tire bursts while driving: grip the wheel, slow gently, avoid harsh braking"],
  "How to change a tyre - The AA","https://www.theaa.com/breakdown-cover/advice/change-a-flat-tyre"),
 ("overheating","Engine overheating",[
  "If the temperature gauge rises, turn the heater up full as a temporary fix.",
  "A red temperature light means pull over somewhere safe.",
  "Switch off and let the engine cool for at least 30 minutes, longer if it overheated.",
  "Don't remove the radiator or coolant cap unless the engine is cold: pressurised hot water can scald.",
  "When cold, check the coolant tank is between min and max; water only as an emergency top-up.",
  "Have the car checked at a garage: coolant should not drop."],
  ["Steam or smoke from the engine: keep away from the bonnet; cooling fans can start even with the key out"],
  "How to check your engine coolant - The AA","https://www.theaa.com/breakdown-cover/advice/how-to-check-your-engine-coolant"),
 ("carBattery","Dead car battery: jump-starting",[
  "Park the cars close without touching; handbrakes on, ignitions off.",
  "Red lead: good battery positive (+) to flat battery positive (+).",
  "Black lead: good battery negative (-) to bare metal on your car, away from the battery and fuel system.",
  "Wait 3 minutes, run the donor car for 1 minute, then start your car.",
  "Let both idle about 10 minutes, switch off, remove the leads in reverse order.",
  "Still won't start? Call for professional help. Otherwise drive at least 30 minutes to recharge."],
  ["Never jump a damaged or leaking battery; stop if the leads get hot","No smoking or flames near batteries; keep rings, watches and tools away","Never let the lead ends touch each other"],
  "How to jump start a car - The AA","https://www.theaa.com/breakdown-cover/advice/using-jump-leads"),
 ("wontStart","Car won't start: basic checks",[
  "Rapid clicking usually means a flat battery: try a jump start.",
  "A single click suggests a starter motor or relay problem: you'll need a mechanic.",
  "Cranks but won't start? Check fuel; the engine may be flooded or the tank empty.",
  "Flashing key symbol: hold the key fob against the start button, or try the spare key.",
  "Key won't turn: rock the steering wheel to free the lock; don't force it.",
  "Press the clutch or brake pedal fully down."],
  ["Smoke from under the bonnet: stop trying and get a mechanic","Don't keep turning the key for a long time; it can cause damage"],
  "Car won't start - The AA","https://www.theaa.com/breakdown-cover/advice/starting-a-car"),
 ("warningLights","Dashboard warning lights",[
  "Red means act now; amber means get it checked at a garage; green is OK.",
  "Oil pressure light: stop as soon as possible and check the oil; if it stays on, engine off and get help.",
  "Red temperature light: pull over safely and check the coolant (only when the engine is cold).",
  "Brake light: check the handbrake is off; if the pedal goes further than usual, pull over and get help.",
  "Red battery light: stop safely, switch off, and don't restart.",
  "Flashing engine light: avoid hard acceleration, stop safely; if still flashing after a restart, get help."],
  ["Brake and ABS lights on together: slow gradually, stop, and don't drive until it's fixed"],
  "Dashboard warning lights and what they mean - The AA","https://www.theaa.com/breakdown-cover/advice/dashboard-warning-lights"),
]
out = {"schemaVersion": 1,
 "note": "Steps are short paraphrases of the linked public sources (fetched 2026-10-09), not medical advice. UK sources say 999 (and assume driving on the left); the app shows 911, the Philippine emergency hotline, and UK motorway-specific advice is left out, the Philippine emergency hotline. 'Life Off Desk app guidance' cards describe app features only. Founder review recommended before release.",
 "cards": [dict(topic=t, title=ti, steps=st, callNow=cn, sourceTitle=sti, sourceURL=su) for t,ti,st,cn,sti,su in cards]}
open(__import__('pathlib').Path(__file__).resolve().parents[1]/'LifeOffDesk/Resources/StarterData/safety-guide.json','w').write(json.dumps(out, ensure_ascii=False, indent=1)+'\n')
print(len(cards))
