#!/usr/bin/env python3
"""Writes LifeOffDesk/Resources/StarterData/safety-guide.json: help cards paraphrased from the linked public sources (see docs/SAFETY-GUIDE.md). Edit cards here, then run it."""
import json
APP = ("Life Off Desk app guidance (not medical)", "https://github.com/lewisjohnvillamor/Lifeoffdesk/blob/main/docs/SAFETY-GUIDE.md")
cards = [
 ("bleeding","Cuts and bleeding",[
  "Wash and dry your hands; wear disposable gloves if you have them.",
  "Press on the wound with a bandage or clean folded cloth.",
  "If something is stuck in it, leave it in and press firmly on either side.",
  "Raise an injured arm above head level; for a leg, lie down and raise it above the heart.",
  "If blood soaks through, add another pad on top and keep pressing.",
  "Every 10 minutes check the bandage isn't too tight."],
  ["The bleeding won't stop","Bright red blood spurts out","Numbness near the wound or trouble moving it","A very large or deep wound, or one on the face or palm","An object like glass is stuck in it"],
  "Cuts and grazes - NHS","https://www.nhs.uk/conditions/cuts-and-grazes/"),
 ("burn","Burns and scalds",[
  "Cool the burn under cool running water for 20 minutes.",
  "No tap? Use cool bottled water or a wet towel.",
  "Remove clothing or jewellery near the burn, but not anything stuck to it.",
  "Once cooled, lay cling film loosely over it; don't wrap it around.",
  "Don't use creams, oil, butter, plasters or sticky dressings; don't burst blisters."],
  ["The burn is very large or deep","It is on the face, genitals or bottom","It was caused by acid, chemicals or electricity"],
  "Burns and scalds - NHS","https://www.nhs.uk/conditions/burns-and-scalds/"),
 ("sprain","Sprains, twisted ankles and possible broken bones",[
  "Protect: support the injury, for example with supportive shoes.",
  "Rest: stop and avoid putting weight on it.",
  "Ice: a wrapped ice pack for up to 20 minutes, every 2–3 hours.",
  "Compression: wrap a bandage around it for support during the day.",
  "Elevate: keep it raised on a pillow as much as possible.",
  "For the first couple of days avoid heat, alcohol and massage."],
  ["You heard a crack when it happened","The limb looks misshapen or at an odd angle","It is numb or tingling","The skin is blue, grey or cold"],
  "Sprains and strains - NHS","https://www.nhs.uk/conditions/sprains-and-strains/"),
 ("heat","Heat exhaustion and heatstroke",[
  "Move the person somewhere cool.",
  "Remove unnecessary clothing like jackets or socks.",
  "Give plenty of water; a sports drink or oral rehydration solution also helps.",
  "Spray or sponge with cool water and fan them; put wrapped cold packs on armpits or neck.",
  "Stay with them; they should feel better within 30 minutes.",
  "If unconscious, use the recovery position; give CPR if there are no signs of life."],
  ["Still unwell after 30 minutes of cooling and fluids","Hot skin that isn't sweating","Fast heartbeat or fast breathing","Confusion or poor coordination","A seizure or loss of consciousness"],
  "Heat exhaustion and heatstroke - NHS","https://www.nhs.uk/conditions/heat-exhaustion-heatstroke/"),
 ("fainting","Fainting and feeling faint",[
  "Feeling faint? Lie down with legs raised, or sit with your head between your knees.",
  "Drink some water; cross your legs, rock on your toes or clench your fists.",
  "If someone faints, gently shake their shoulders and ask loudly if they're OK.",
  "No response: shout for help, tilt the head back and lift the chin.",
  "Check breathing for 10 seconds; if normal, lay them on their back with legs raised.",
  "Most people wake within 30 seconds."],
  ["They are not breathing","They can't be woken within 1 minute","Trouble speaking or moving, chest pain or palpitations","A seizure, a serious injury, or fainting while exercising or lying down"],
  "Fainting - NHS","https://www.nhs.uk/symptoms/fainting/"),
 ("stroke","Stroke: think FAST",[
  "Face: has one side of the face drooped? Ask them to smile.",
  "Arms: can they lift both arms and keep them up? One may be weak or numb.",
  "Speech: is their speech slurred or confused?",
  "Time: call 911 straight away, even if the signs stop. Note the time they started.",
  "Don't drive them to the hospital yourself if an ambulance can come; follow the call handler's instructions."],
  ["Any FAST sign, now or in the last 24 hours","Sudden weakness or numbness down one side, blurred or lost vision","Sudden confusion, dizziness, falling over or a severe headache"],
  "Symptoms of a stroke - NHS","https://www.nhs.uk/conditions/stroke/symptoms/"),
 ("heartAttack","Heart attack and chest pain",[
  "Call 911 now if the chest pain is tight, crushing or spreads to the arm, neck or jaw.",
  "Have them rest on the floor with knees bent and back supported, or sit in a chair.",
  "Aspirin 300 mg, if available: the source says take it unless they are allergic to aspirin.",
  "If they have angina medicine (a GTN spray), they should use it.",
  "Keep checking they respond and breathe; if they stop, start CPR."],
  ["Tight or squeezing chest pain, or pain spreading to arm, neck, jaw or back","Severe difficulty breathing","Pale, blue or grey lips or skin","They pass out or don't respond normally"],
  "Heart attack - NHS","https://www.nhs.uk/conditions/heart-attack/"),
 ("seizure","Seizure (fit)",[
  "Stay calm; only move them if they are in danger, like near a road.",
  "Cushion their head and loosen anything tight around the neck.",
  "Don't hold them down and don't put anything in their mouth, not even fingers.",
  "Note when it starts and stops.",
  "When the shaking stops, put them on their side (recovery position) and stay until they recover.",
  "No food or drink until they have fully recovered."],
  ["It is their first seizure","It lasts more than 5 minutes (or longer than usual for them)","They don't wake fully, or have seizures one after another","They are seriously hurt or have trouble breathing afterwards"],
  "What to do if someone has a seizure (fit) - NHS","https://www.nhs.uk/symptoms/what-to-do-if-someone-has-a-seizure-fit/"),
 ("nosebleed","Nosebleed",[
  "Sit down and lean forward, head tilted forward, mouth open.",
  "Pinch the soft part of the nose just above the nostrils for 10–15 minutes.",
  "Breathe through your mouth while pinching.",
  "A wrapped ice pack on the bridge of the nose may help.",
  "For 24 hours after, don't blow or pick your nose, and avoid hot drinks, alcohol and heavy lifting."],
  ["Bleeding lasts more than 10–15 minutes or seems a lot","You swallow so much blood you vomit","It started after a blow to the head","You feel weak or dizzy, or have trouble breathing"],
  "Nosebleed - NHS","https://www.nhs.uk/conditions/nosebleed/"),
 ("headache","Headache and migraine",[
  "Drink plenty of water.",
  "Rest and try to relax; stress can make headaches worse.",
  "Take paracetamol or ibuprofen if needed.",
  "Don't skip meals, even if you're not hungry.",
  "Avoid long screen time, alcohol and oversleeping."],
  ["A sudden, extremely painful headache","With a seizure, numbness or weakness, slurred speech, poor balance or confusion","With vision loss, a rash that doesn't fade under a glass, or a stiff neck with high fever","After a head injury, or the person is very drowsy"],
  "Headaches - NHS","https://www.nhs.uk/symptoms/headaches/"),
 ("eyeInjury","Something in the eye or eye injury",[
  "Rinse the eye with clean, lukewarm water (tap, shower or bottled).",
  "Hold the eye open and run a gentle stream of water over it for at least 20 minutes.",
  "For a household or cosmetic product, follow the advice on the packaging.",
  "Don't touch or rub the eye; leave out contact lenses and eye make-up.",
  "Never try to remove an object stuck in the eye."],
  ["A strong chemical like bleach got in the eye: keep rinsing and bring the container","Something sharp pierced the eye or hit it at high speed","Vision changes, severe pain, or light hurts the eye","You can't open or move the eye, or there is blood or pus"],
  "Eye injuries - NHS","https://www.nhs.uk/conditions/eye-injuries/"),
 ("blisters","Blisters from walking",[
  "Don't pop the blister yourself.",
  "Gently wash the area and pat it dry.",
  "Cover it with a soft plaster or padded dressing.",
  "If it bursts, wash your hands, let it drain, then cover it; don't peel off the loose skin.",
  "Stop wearing the shoes that caused it; well-fitting shoes and thick socks help prevent them."],
  ["The skin is hot and red, or there is green or yellow pus","It is very painful or keeps coming back","It came from a burn, sunburn or an allergic reaction"],
  "Blisters - NHS","https://www.nhs.uk/conditions/blisters/"),
 ("cramps","Muscle cramps (pulikat)",[
  "Stretch and massage the cramping muscle.",
  "Stand up and put your weight on the affected leg.",
  "Most cramps stop on their own within seconds to 10 minutes.",
  "Afterwards, paracetamol or ibuprofen can ease soreness for up to a day.",
  "Drink water; dehydration and hard exercise in heat can trigger cramps."],
  ["A cramp lasts longer than 10 minutes","There is also numbness or swelling in the leg","Cramps keep coming back"],
  "Leg cramps - NHS","https://www.nhs.uk/conditions/leg-cramps/"),
 ("foodPoisoning","Food poisoning, diarrhea and vomiting",[
  "Rest and drink plenty of fluids; take small sips if you feel sick.",
  "Use oral rehydration salts (ORS) if you pee less or your pee is dark.",
  "Eat when you can; avoid fatty or spicy food, fruit juice and fizzy drinks.",
  "Paracetamol can ease discomfort.",
  "Wash your hands often with soap and don't prepare food for others."],
  ["Vomiting blood, or vomit that looks like coffee grounds or is green","Sudden severe headache or stomach pain, or a stiff neck","Blue, grey or pale lips or skin, or severe trouble breathing","You can't keep any fluids down, or there is blood in the diarrhea"],
  "Diarrhoea and vomiting - NHS","https://www.nhs.uk/symptoms/diarrhoea-and-vomiting/"),
 ("roadCrash","Road accident: helping safely",[
  "Park well away from the scene, hazard lights on; stay visible.",
  "Get others to warn traffic in both directions.",
  "Turn off damaged vehicles' ignition and apply handbrakes.",
  "Call 911: say how many are hurt, their ages and their injuries.",
  "Treat life-threatening injuries first; check for other casualties nearby.",
  "Keep checking each person's breathing and response until help arrives."],
  ["Assume a neck or spine injury: treat people where they lie and support the head and neck","Leave trapped people to rescuers; don't try to move an overturned vehicle","Watch for traffic, fuel spills and damaged power lines; no smoking nearby"],
  "How to Manage a Traffic Accident | St John Ambulance","https://www.sja.org.uk/first-aid-advice/traffic-collision/"),
 ("fire","Fire: get out and stay out",[
  "Shout \"Fire!\" and get outside immediately; leave belongings behind.",
  "Take the stairs, not the elevator.",
  "If a door or handle feels warm, or smoke blocks the way, use another exit.",
  "In smoke, stay low and close doors behind you.",
  "If trapped, stay in a closed room, put a wet towel under the door and call for help.",
  "Signal from a window with a bright cloth or flashlight."],
  ["Never go back inside for anything or anyone","Never open a door that is warm to the touch","If your clothes catch fire: stop, drop, cover your face and roll"],
  "What To Do If A Fire Starts | American Red Cross","https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/fire/if-a-fire-starts.html"),
 ("earthquake","Earthquake (lindol)",[
  "Drop to your hands and knees, cover your head and neck, and hold on.",
  "Get under a sturdy table and grip it, or go to an inside wall away from windows.",
  "Outdoors: move to open space away from buildings, power lines and trees.",
  "Driving: stop away from buildings, overpasses and wires; stay in the vehicle.",
  "After the shaking, put on sturdy shoes; leave only if outside is clear and safe.",
  "If trapped, cover your mouth and nose and knock or whistle three times every few minutes."],
  ["Near the coast, walk to higher ground as soon as shaking stops; don't wait for a tsunami warning","Use a flashlight, not candles or matches, until you're sure there's no gas leak","Expect aftershocks; leave a damaged building"],
  "Earthquake Safety | Red Cross","https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/earthquake.html"),
 ("typhoon","Typhoon (bagyo)",[
  "If authorities advise evacuation, take your emergency kit and leave right away.",
  "Follow official evacuation routes; shortcuts may be blocked.",
  "Shelter in a small inside room with no windows, on a floor that won't flood.",
  "Stay away from glass windows and doors.",
  "Move to higher ground before flooding begins.",
  "Secure outdoor items that strong winds could throw."],
  ["Never walk, swim or drive through floodwater","Avoid downed power lines and don't touch floodwater","Never run gas, charcoal or generators indoors","Don't go home until officials say it's safe"],
  "Hurricane Preparedness | Red Cross (typhoons are the same storms)","https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/hurricane.html"),
 ("powerOutage","Brownout or power outage",[
  "Use flashlights, not candles.",
  "Unplug appliances and electronics to avoid damage when power returns.",
  "Keep the fridge closed; it stays cold for about 4 hours.",
  "Check local alerts and make sure family and neighbours are OK.",
  "Run generators only outdoors, away from windows.",
  "Go somewhere else if it gets too hot or a medical device needs power."],
  ["Stay far from fallen power lines and report them","Never cook or heat with gas stoves indoors (carbon monoxide)","Don't use electrical equipment that got wet; throw out food that got warm"],
  "Power Outage Safety | American Red Cross","https://www.redcross.org/get-help/how-to-prepare-for-emergencies/types-of-emergencies/power-outage.html"),
 ("asthma","Asthma attack (hika)",[
  "Sit upright and try to stay calm.",
  "Take one puff of the blue reliever inhaler every 30–60 seconds, up to 10 puffs.",
  "If not better after 10 puffs, or worse at any point, call 911.",
  "If help hasn't arrived after 10 minutes and it isn't improving, repeat the puffs.",
  "Helping someone: reassure them, help them sit comfortably and use their inhaler.",
  "Afterwards, see a doctor the same day even if they feel better."],
  ["Symptoms get worse at any point","No better after 10 puffs","No inhaler and struggling to breathe"],
  "Asthma attacks | Asthma + Lung UK","https://www.asthmaandlung.org.uk/conditions/asthma/asthma-attacks"),
 ("lowBloodSugar","Low blood sugar (diabetes)",[
  "Check blood sugar if you can; treat if it's low or there are symptoms.",
  "Give fast sugar: a small glass of juice or sugary drink, or glucose tablets.",
  "Recheck after 10–15 minutes; if still low, give more sugar.",
  "Once better, have a longer-lasting snack like bread or biscuits, or a meal.",
  "If unconscious: give nothing by mouth and put them in the recovery position.",
  "Stay with them until fully recovered."],
  ["They are unconscious or not responding","They have a seizure","They have been drinking alcohol"],
  "Low blood sugar (hypoglycaemia) - NHS","https://www.nhs.uk/conditions/low-blood-sugar-hypoglycaemia/"),
 ("mosquito","Mosquito bites and dengue",[
  "Dengue mosquitoes bite in the daytime: cover as much skin as possible.",
  "Use repellent with DEET, picaridin or IR3535; screens, coils or nets help.",
  "Empty, cover and clean water containers every week.",
  "If dengue is suspected: rest, drink plenty of fluids, paracetamol for pain.",
  "Avoid ibuprofen and aspirin; they raise bleeding risk.",
  "Watch for warning signs, especially after the fever goes away."],
  ["Severe stomach pain or vomiting that won't stop","Bleeding gums or nose, or blood in vomit or stool","Fast breathing, restlessness, or pale cold skin","Marked tiredness or weakness"],
  "Dengue and severe dengue - WHO","https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue"),
 ("sunburn","Sunburn",[
  "Get out of the sun as soon as possible.",
  "Cool the skin with a cool shower or damp towel.",
  "Apply aftersun or an unperfumed moisturiser; no ice or petroleum jelly.",
  "Drink plenty of water and avoid alcohol.",
  "Paracetamol or ibuprofen can help with pain.",
  "Keep burnt skin covered; don't pop blisters or pick peeling skin."],
  ["The skin is blistered or swollen","A very high temperature, or feeling hot, cold and shivery","Dizzy, sick, headache or cramps (possible heat exhaustion)","A baby or young child is sunburnt"],
  "Sunburn - NHS","https://www.nhs.uk/conditions/sunburn/"),
 ("sparkPlug","Changing a spark plug",[
  "Park on level ground, handbrake on, and wait until the engine is cold.",
  "Open the hood; twist and pull each wire or coil off its plug.",
  "Unscrew the old plug with a spark plug socket.",
  "Thread the new plug in by hand first to avoid cross-threading.",
  "Tighten it with the socket, then refit the coils, wires and connectors.",
  "Start the engine and listen for anything unusual."],
  ["Only work on a cold engine","Starting the plug by hand protects the engine head","Diesel engines have glow plugs, not spark plugs","Unsure, or problems after? Use a mechanic"],
  "Spark plugs maintenance and replacement guide - RAC","https://www.rac.co.uk/drive/advice/car-maintenance/what-are-spark-plugs-maintenance-and-replacement-guide/"),
 ("choking","Choking (adult)",[
  "Ask \"are you choking?\" If they can breathe, speak or cough, let them cough.",
  "Remove any obvious blockage from the mouth.",
  "If coughing fails, lean them forward and give five sharp back blows between the shoulder blades.",
  "Check the mouth after each back blow.",
  "Still blocked: stand behind, fist between belly button and chest, pull sharply in and up, up to five times.",
  "Keep repeating five back blows and five thrusts until help arrives."],
  ["The blockage hasn't cleared after back blows and thrusts","They become unresponsive (start CPR)"],
  "Choking | St John Ambulance","https://www.sja.org.uk/first-aid-advice/choking/"),
 ("cpr","CPR (adult, not breathing)",[
  "Make sure it's safe; shake their shoulders and ask loudly \"are you OK?\"",
  "No response: shout for help, tilt the head back, check normal breathing for up to 10 seconds.",
  "Not breathing normally: have someone call 911 on speaker and find a defibrillator.",
  "Heel of your hand mid-chest, other hand on top, arms straight, press down 5–6 cm.",
  "Push 100–120 times a minute. Not trained? Keep giving continuous chest compressions.",
  "Continue until help takes over, they breathe normally, or you are exhausted."],
  ["An adult is unresponsive and not breathing normally (occasional gasps are not normal breathing)"],
  "How to do CPR | St John Ambulance","https://www.sja.org.uk/get-advice/first-aid-advice/unresponsive-casualty/how-to-do-cpr-on-an-adult/"),
 ("allergy","Severe allergic reaction (anaphylaxis)",[
  "Use an adrenaline auto-injector (e.g. EpiPen) if there is one; instructions are on the side.",
  "Call 911 and say you think it's anaphylaxis.",
  "Lie down with legs raised; if breathing is hard, sit up slowly.",
  "If stung, remove the sting if it's still in the skin.",
  "No improvement after 5 minutes: use a second auto-injector.",
  "Never stand or walk, even if feeling better."],
  ["Lips, mouth, throat or tongue suddenly swell","Breathing is fast or a struggle, or the throat feels tight","Skin, tongue or lips turn blue, grey or pale","Sudden confusion, drowsiness, or fainting"],
  "Anaphylaxis - NHS","https://www.nhs.uk/conditions/anaphylaxis/"),
 ("animalBite","Dog or cat bite or scratch (rabies risk)",[
  "Wash the wound right away with soap or detergent.",
  "Flush it with plenty of water for about 15 minutes.",
  "Then apply an iodine-containing or antiviral antiseptic if you have one.",
  "Don't put chili, plant juices, acids or alkalis on it.",
  "Go to a health facility for assessment and rabies treatment; don't wait.",
  "If it's safe, keep the animal confined and watch it for 10 days."],
  ["Any bite or scratch from an animal that could have rabies: get medical care today","A large or deep wound, or bleeding that won't stop"],
  "Rabies - World Health Organization","https://www.who.int/health-topics/rabies"),
 ("dehydration","Dehydration",[
  "Drink fluids if you are thirsty, dizzy, tired, or your pee is dark.",
  "If you feel sick, start with small sips and slowly drink more.",
  "Avoid caffeine and alcohol.",
  "With vomiting or diarrhoea, use oral rehydration solution.",
  "Drink more in hot weather or when exercising; aim for pale pee."],
  ["Blue, grey, pale or blotchy skin, lips or tongue, or cold skin","Difficulty breathing or rapid breaths","Confusion, or being unusually sleepy or hard to wake"],
  "Dehydration - NHS","https://www.nhs.uk/conditions/dehydration/"),
 ("sting","Insect and bee stings",[
  "Scrape the stinger out sideways with a fingernail or card edge.",
  "Don't use tweezers; squeezing can push in more venom.",
  "Wash the area with soap and water.",
  "Hold a wrapped ice pack or cold wet cloth on it for at least 20 minutes; raise it.",
  "Don't scratch."],
  ["Stung in the mouth, throat or near the eyes","Stung many times, or a serious reaction before","Any sign of anaphylaxis: swelling of lips or throat, trouble breathing"],
  "Insect bites and stings - NHS","https://www.nhs.uk/conditions/insect-bites-and-stings/"),
 ("snakeBite","Snake bite",[
  "Treat every snake bite as an emergency: call 911 or go to a hospital.",
  "Stay calm and keep the bitten part as still as possible.",
  "Remove jewellery and loosen clothing near the bite.",
  "Remember the snake's colour and pattern, or photograph it from a safe distance.",
  "Don't catch or kill the snake, suck or cut the bite, or tie anything tight around it."],
  ["Any snake bite"],
  "Snake bites - NHS (UK page; outside the UK use local emergency services)","https://www.nhs.uk/conditions/snake-bites/"),
 ("wildPlants","Wild plants, berries and mushrooms",[
  "This app cannot identify plants or mushrooms, and a description is not enough to know one is safe.",
  "Some plants and mushrooms are poisonous; if someone may have eaten one, call 911 or go to a hospital.",
  "Don't make them vomit, and don't give them anything to eat or drink.",
  "Keep a sample of what was eaten to show the doctors.",
  "If unconscious but breathing, use the recovery position; if not breathing, start CPR."],
  ["Something harmful may have been eaten (symptoms can take hours or days)","Unconscious, not breathing, or breathing is very difficult","A seizure"],
  "Poisoning - NHS","https://www.nhs.uk/conditions/poisoning/"),
 ("flood","Floods (baha)",[
  "Don't walk or drive through flooded areas or standing water.",
  "Hidden dangers include fallen power lines and chemicals; currents can sweep people away.",
  "Know your community's evacuation route and flood-prone areas.",
  "Wash hands with soap after touching floodwater; never use it for food, dishes or teeth.",
  "Throw away food that touched floodwater; boil or chlorinate drinking water."],
  ["Someone is trapped or swept away by water","Live wires are down in or near the water"],
  "Floods: How to protect your health - WHO","https://www.who.int/news-room/questions-and-answers/item/how-do-i-protect-my-health-in-a-flood"),
 ("lightning","Lightning and thunderstorms",[
  "When thunder roars, go indoors: hearing thunder means you're within striking distance.",
  "Only an enclosed building or a car is safe; tents and open shelters are not.",
  "Wait 30 minutes after the last thunder before going back outside.",
  "If stuck outside, avoid open fields, hilltops and tall isolated trees.",
  "Groups should spread out; stay away from water and metal fences or poles."],
  [],
  "Lightning Safety - US National Weather Service","https://www.weather.gov/safety/lightning-safety"),
 ("unsafe","Feeling unsafe, followed or threatened",[
  "If you are in danger now, call 911.",
  "Go towards people and lit, busy places such as a store, guard post or police station.",
  "In this Help screen, the nearest police stations have a Route button (offline).",
  "Copy or text your location from this screen to someone you trust (SMS works without data)."],
  ["You or someone else is in immediate danger"],
  *APP),
 ("lost","Lost or not sure where you are",[
  "Stay calm and stop walking for a moment.",
  "Tap Locate on the map; your position works offline while GPS has a fix.",
  "Copy or text your location from this Help screen to someone you trust.",
  "Pick a place on the map and follow the dashed suggested route along mapped streets."],
  ["You are hurt, in danger, or it is getting dark somewhere unsafe"],
  *APP),
 ("phoneBattery","Phone battery running low",[
  "Turn on Low Power Mode: Settings › Battery (or Control Center, battery icon).",
  "Low Power Mode dims the screen and pauses background tasks to save battery.",
  "With no signal, Airplane Mode stops the phone searching for a network, which drains battery.",
  "Before it runs out, text your location to someone you trust."],
  [],
  "Use Low Power Mode to save battery life on your iPhone - Apple Support","https://support.apple.com/en-us/101604"),
 ("noGPS","Location not updating",[
  "This app works without data; GPS itself needs no signal or internet.",
  "If the app says \"Finding your location…\", move to an open area away from tall buildings and wait a moment.",
  "Check Settings › Privacy & Security › Location Services is on for Life Off Desk.",
  "Your last saved adventure and the map still work while the location catches up."],
  [],
  *APP),
 ("breakdown","Vehicle breakdown: stay safe first",[
  "Get the vehicle off the road if you can, ideally a parking area or lay-by.",
  "Turn on hazard lights if the vehicle is blocking traffic.",
  "Wear light or reflective clothing; keep sidelights on if it's dark.",
  "Place a warning triangle at least 45 m behind the vehicle, on the same side.",
  "Passengers should keep well away from the vehicle and moving traffic.",
  "Never stand between your vehicle and oncoming traffic."],
  ["You can't get out safely: stay inside with seat belts and hazards on, and call 911","On a high-speed road: don't attempt repairs; get behind a barrier"],
  "The Highway Code: Breakdowns and incidents - GOV.UK","https://www.gov.uk/guidance/the-highway-code/breakdowns-and-incidents-274-to-287"),
 ("flatTire","Flat tire (gulong): changing to the spare",[
  "Park somewhere safe away from traffic: engine off, hazards on, handbrake on, in park or first gear.",
  "Loosen the wheel nuts slightly before jacking the car up.",
  "Jack at the marked jacking point (see the handbook) on level ground until the wheel is off the ground.",
  "Remove the nuts and wheel, fit the spare, hand-tighten the nuts in a diagonal pattern.",
  "Lower the car, tighten the nuts firmly, then check the tire pressure.",
  "Go to a vulcanizing or tire shop soon; space-saver spares are usually limited to about 80 km/h."],
  ["Never change a tire on an expressway shoulder or next to fast traffic","If the wheel won't come off easily, refit the nuts and call for help","If a tire bursts while driving: grip the wheel, slow gently, avoid harsh braking"],
  "How to change a tyre - The AA","https://www.theaa.com/breakdown-cover/advice/change-a-flat-tyre"),
 ("overheating","Engine overheating",[
  "If the temperature gauge rises, turn the heater up full as a temporary fix.",
  "A red temperature light means pull over somewhere safe.",
  "Switch off and let the engine cool for at least 30 minutes, longer if it overheated.",
  "Don't remove the radiator or coolant cap unless the engine is cold: pressurised hot water can scald.",
  "When cold, check the coolant tank is between min and max; water only as an emergency top-up.",
  "Have the car checked at a garage: coolant should not drop."],
  ["Steam or smoke from the engine: keep away from the bonnet; cooling fans can start even with the key out"],
  "How to check your engine coolant - The AA","https://www.theaa.com/breakdown-cover/advice/how-to-check-your-engine-coolant"),
 ("carBattery","Dead car battery: jump-starting",[
  "Park the cars close without touching; handbrakes on, ignitions off.",
  "Red lead: good battery positive (+) to flat battery positive (+).",
  "Black lead: good battery negative (-) to bare metal on your car, away from the battery and fuel system.",
  "Wait 3 minutes, run the donor car for 1 minute, then start your car.",
  "Let both idle about 10 minutes, switch off, remove the leads in reverse order.",
  "Still won't start? Call for professional help. Otherwise drive at least 30 minutes to recharge."],
  ["Never jump a damaged or leaking battery; stop if the leads get hot","No smoking or flames near batteries; keep rings, watches and tools away","Never let the lead ends touch each other"],
  "How to jump start a car - The AA","https://www.theaa.com/breakdown-cover/advice/using-jump-leads"),
 ("wontStart","Car won't start: basic checks",[
  "Rapid clicking usually means a flat battery: try a jump start.",
  "A single click suggests a starter motor or relay problem: you'll need a mechanic.",
  "Cranks but won't start? Check fuel; the engine may be flooded or the tank empty.",
  "Flashing key symbol: hold the key fob against the start button, or try the spare key.",
  "Key won't turn: rock the steering wheel to free the lock; don't force it.",
  "Press the clutch or brake pedal fully down."],
  ["Smoke from under the bonnet: stop trying and get a mechanic","Don't keep turning the key for a long time; it can cause damage"],
  "Car won't start - The AA","https://www.theaa.com/breakdown-cover/advice/starting-a-car"),
 ("warningLights","Dashboard warning lights",[
  "Red means act now; amber means get it checked at a garage; green is OK.",
  "Oil pressure light: stop as soon as possible and check the oil; if it stays on, engine off and get help.",
  "Red temperature light: pull over safely and check the coolant (only when the engine is cold).",
  "Brake light: check the handbrake is off; if the pedal goes further than usual, pull over and get help.",
  "Red battery light: stop safely, switch off, and don't restart.",
  "Flashing engine light: avoid hard acceleration, stop safely; if still flashing after a restart, get help."],
  ["Brake and ABS lights on together: slow gradually, stop, and don't drive until it's fixed"],
  "Dashboard warning lights and what they mean - The AA","https://www.theaa.com/breakdown-cover/advice/dashboard-warning-lights"),
]
out = {"schemaVersion": 1,
 "note": "Steps are short paraphrases of the linked public sources (fetched 2026-10-09), not medical advice. UK sources say 999 (and assume driving on the left); the app shows 911, the Philippine emergency hotline, and UK motorway-specific advice is left out, the Philippine emergency hotline. 'Life Off Desk app guidance' cards describe app features only. Founder review recommended before release.",
 "cards": [dict(topic=t, title=ti, steps=st, callNow=cn, sourceTitle=sti, sourceURL=su) for t,ti,st,cn,sti,su in cards]}
open(__import__('pathlib').Path(__file__).resolve().parents[1]/'LifeOffDesk/Resources/StarterData/safety-guide.json','w').write(json.dumps(out, ensure_ascii=False, indent=1)+'\n')
print(len(cards))
